In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 200)
df = pd.read_csv('ready_data00.csv', low_memory=False)
df.head(1)

,country_or_area,commodity_transaction,year,unit,quantity,quantity_footnotes,category,commodity,transaction_type,additional_transaction_info
0,Austria,Additives and Oxygenates - Exports,1996,"Metric tons, thousand",5.0,NaN,additives_and_oxygenates,additives and oxygenates,exports,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032032 entries, 0 to 1032031
Data columns (total 10 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   country_or_area              1032032 non-null  object
 1   commodity_transaction        1032032 non-null  object
 2   year                         1032032 non-null  int64
 3   unit                         1032032 non-null  object
 4   quantity                     1032032 non-null  float64
 5   quantity_footnotes           130232 non-null   float64
 6   category                     1032032 non-null  object
 7   commodity                    1032032 non-null  object
 8   transaction_type             1026856 non-null  object
 9   additional_transaction_info  43536 non-null    object
dtypes: float64(2), int64(1), object(7)
memory usage: 78.7+ MB

In [3]:
df.transaction_type = df.transaction_type + ' ' + df.additional_transaction_info.fillna('')
df.transaction_type = df.transaction_type.str.strip()

In [4]:
df.commodity = df.commodity.astype('category')
df.transaction_type = df.transaction_type.astype('category')
df.country_or_area = df.country_or_area.astype('category')
df.commodity_transaction = df.commodity_transaction.astype('category')
df.unit = df.unit.astype('category')
df.category = df.category.astype('category')
df.year = df.year.astype('category')
df.quantity = df.quantity.astype('float32')
df.quantity_footnotes = df.quantity_footnotes.astype('float32')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032032 entries, 0 to 1032031
Data columns (total 10 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   country_or_area              1032032 non-null  category
 1   commodity_transaction        1032032 non-null  category
 2   year                         1032032 non-null  category
 3   unit                         1032032 non-null  category
 4   quantity                     1032032 non-null  float32
 5   quantity_footnotes           130232 non-null   float32
 6   category                     1032032 non-null  category
 7   commodity                    1032032 non-null  category
 8   transaction_type             1026856 non-null  category
 9   additional_transaction_info  43536 non-null    object
dtypes: category(7), float32(2), object(1)
memory usage: 25.7+ MB

In [5]:
only_comm = df.loc[:,['country_or_area','year',"transaction_type",'unit', 'quantity', 'category']]
only_comm.head()

,country_or_area,year,transaction_type,unit,quantity,category
0,Austria,1996,exports,"Metric tons, thousand",5.0,additives_and_oxygenates
1,Austria,1995,exports,"Metric tons, thousand",17.0,additives_and_oxygenates
2,Belgium,2014,exports,"Metric tons, thousand",0.0,additives_and_oxygenates
3,Belgium,2013,exports,"Metric tons, thousand",0.0,additives_and_oxygenates
4,Belgium,2012,exports,"Metric tons, thousand",35.0,additives_and_oxygenates

In [6]:
only_comm["transaction_type"].value_counts().sort_index()

additional resources                                                                     169
autoproducer                                                                            6682
autoproducer chp plants                                                                 1636
autoproducer electricity plants                                                         1898
autoproducer heat plants                                                                 699
autoproducer total                                                                       662
changes in stocks                                                                        643
commercial and public services                                                            53
consumption by agriculture, forestry and fishing                                       13227
consumption by briquetting plants                                                         40
consumption by chemical                                                                   42
consumption by chemical and petrochemical                                              10605
consumption by coal mines                                                                113
consumption by commercial and public services                                          14051
consumption by construction                                                             5584
consumption by domestic aviation                                                        3909
consumption by domestic navigation                                                      3161
consumption by electricity, chp and heat plants                                            9
consumption by energy sector                                                              57
consumption by food and tobacco                                                         8291
consumption by food, beverage and tobacco                                                252
consumption by households                                                              27921
consumption by iron and steel                                                          10709
consumption by lng/regasification plants                                                   3
consumption by machinery                                                                6357
consumption by manufacturing, construction and non-fuel                                34340
consumption by mining and quarrying                                                     5354
consumption by non-ferrous metals                                                       4885
consumption by non-metallic minerals                                                    9845
consumption by other                                                                   37679
consumption by other consumers                                                          1319
consumption by other consumers not elsewhere specified                                  1219
consumption by other manuf., const. and non-fuel                                       30408
consumption by other manufacturing, construction and non-fuel                           1315
consumption by other stries and construction                                             111
consumption by other transport                                                           274
consumption by paper, pulp and print                                                    6945
consumption by pipeline transport                                                        946
consumption by rail                                                                     3924
consumption by road                                                                    12588
consumption by stries not elsewhere specified                                           2828
consumption by stry & construction                                                       119
consumption by textile and leather                                                      5664
consumption by transport                                                               20538
consumption by transport equipment                                                      4136
consumption by wood and wood products                                                   4661
consumption for non-energy use                                                           745
consumption not elsewhere specified (other)                                            10533
consumption not elsewhere specified (stry)                                              9283
consumption not elsewhere specified (transport)                                         2218
conversion in blast furnaces                                                               6
conversion in briquetting plants                                                          18
energy stries own use                                                                  15253
estimated additional reserves                                                             42
exports                                                                                30939
extraction loss shrinkage                                                                590
final consumption                                                                      63026
final energy consumption                                                               58920
flared                                                                                   429
flared and vented                                                                        960
from other sources autoproducers                                                         161
from other sources main activity producers                                               129
from other sources total                                                                 204
gross demand                                                                            5836
gross production                                                                        5832
imports                                                                                52327
international aviation bunkers                                                          4891
international marine bunkers                                                            4665
losses                                                                                 10029
main activity                                                                          13904
main activity chp plants                                                                1962
main activity electricity plants                                                        3538
main activity heat plants                                                               1005
main activity total                                                                     1027
memo: closing stock level (national territory)                                             8
memo: opening stock level (national territory)                                             8
memo:gross production                                                                   1972
net installed capacity of electric power plants public solar                             743
net installed capacity of electric power plants, public combustible fuels               4659
net installed capacity of electric power plants, public geothermal                       435
net installed capacity of electric power plants, public hydro                           3217
net installed capacity of electric power plants, public nuclear                          647
net installed capacity of electric power plants, public tide, wave, marine                53
net installed capacity of electric power plants, public wind                            1278
net installed capacity of electric power plants, self-producer combustible fuels        3121
net installed capacity of electric power plants, self-producer geothermal                 78
net installed capacity of electric power plants, self-producer hydro                    1259
net installed capacity of electric power plants, self-producer nuclear                    17
net installed capacity of electric power plants, self-producer solar                     494
net installed capacity of electric power plants, self-producer tide, wave, marine         16
net installed capacity of electric power plants, self-producer wind                      392
net production                                                                          5831
net transfers                                                                              1
non-energy use                                                                         15572
other energy stry own use                                                               2594
other reserves                                                                             9
other transformation                                                                    2090
other transformation processes not elsewhere classified                                    4
own use by biogas production plants                                                       52
own use by blast furnaces                                                                571
own use by briquetting plants                                                            543
own use by charcoal plants                                                                 3
own use by coal liquefaction plants                                                       40
own use by coal mines                                                                   3023
own use by coke ovens                                                                   2094
own use by electricity, chp and heat plants                                             7742
own use by gas works                                                                     766
own use by gas-to-liquid (gtl) plants                                                      8
own use by gasworks                                                                        2
own use by lng/regasification plants                                                     261
own use by nuclear fuel extraction and processing                                        163
own use by oil and gas extraction                                                       3374
own use by oil refineries                                                               9269
own use by other energy producers                                                         27
own use by pump-storage plants                                                           660
production                                                                             52072
production from off-shore                                                                343
production from plants                                                                  1507
production from refineries                                                             24677
pumped hydro autoproducers                                                                49
pumped hydro main activity producers                                                     508
pumped hydro total                                                                       508
re-injected                                                                              463
reasonably assured reserves                                                               61
receipts from other sources                                                             2584
recoverable                                                                               61
recoverable reserves                                                                     366
refinery capacity                                                                       2563
reserves                                                                                1974
reserves from oil shale                                                                   86
reserves from oil shale and tar sands                                                    119
reserves from tar sands                                                                   55
solar pv autoproducers                                                                   312
solar pv main activity producers                                                         453
solar pv total                                                                           624
solar thermal autoproducers                                                                6
solar thermal main activity producers                                                     46
solar thermal total                                                                       52
stock changes                                                                          28378
total energy supply                                                                    76975
total geothermal production                                                              427
total hydraulic resources                                                                754
total hydro production                                                                  3194
total known reserves                                                                     421
total net installed capacity of electric power plants, autoproducer                     3188
total net installed capacity of electric power plants, combustible fuels                4668
total net installed capacity of electric power plants, geothermal                        454
total net installed capacity of electric power plants, hydro                            3241
total net installed capacity of electric power plants, main activity                    4698
total net installed capacity of electric power plants, main activity & autoproducer     4698
total net installed capacity of electric power plants, nuclear                           647
total net installed capacity of electric power plants, solar                            1038
total net installed capacity of electric power plants, tide, wave, marine                 69
total net installed capacity of electric power plants, wind                             1347
total nuclear production                                                                 647
total production, autoproducer                                                          3108
total production, main activity                                                         4695
total resources                                                                          886
total resources in place                                                                 469
total solar production                                                                   907
total thermal production                                                                4665
total tide, wave production                                                               50
total wproduction                                                                       1297
transfers and recycled products                                                         7127
transformation                                                                         31025
transformation in autoproducer chp plants                                                974
transformation in autoproducer electricity plants                                        554
transformation in autoproducer heat plants                                               503
transformation in blast furnaces                                                         914
transformation in briquetting plants                                                     804
transformation in charcoal plants                                                       2905
transformation in chp plants autoproducers                                              5578
transformation in chp plants main activity producers                                    4265
transformation in coal liquefaction plants                                                52
transformation in coke ovens                                                            1861
transformation in electricity plants autoproducers                                      5916
transformation in electricity plants main activity producers                            8268
transformation in electricity, chp and heat plants                                     21325
transformation in gas works                                                              731
transformation in gas-to-liquid plants                                                    46
transformation in heat plants autoproducers                                             2443
transformation in heat plants main activity producers                                   3276
transformation in main activity chp plants                                               645
transformation in main activity electricity plants                                      1080
transformation in main activity heat plants                                              357
transformation in main activity producer chp plants                                      410
transformation in main activity producer electricity plants                              638
transformation in main activity producer heat plants                                     251
transformation in natural gas blending plants                                            204
transformation in oil refineries                                                        4704
transformation in other energy-producing plants                                           68
transformation in petrochemical plants                                                  1394
used for electric boilers                                                                167
used for electricity production                                                          199
used for heat pumps                                                                      124
vented                                                                                   199
Name: transaction_type, dtype: int64

In [7]:
#CL1214a - CL1214o -> CL1214

other_manuf_const_and_non_fuel_min_ind = ['consumption by non-ferrous metals',
                                          'consumption by non-metallic minerals',
                                          'consumption by transport equipment',
                                          'consumption by machinery',
                                          'consumption by mining and quarrying',
                                          'consumption by food and tobacco',
                                          'consumption by food, beverage and tobacco',
                                          'consumption by paper, pulp and print',
                                          'consumption by wood and wood products',
                                          'consumption by construction',
                                          'consumption by industry & construction',
                                          'consumption by textile and leather', 
                                          'consumption not elsewhere specified (industry)',
                                          'consumption by industries not elsewhere specified'
                                           ]

In [8]:
def CL4(row):
    if row in other_manuf_const_and_non_fuel_min_ind:
        return 'other manuf., const. and non-fuel min. ind.'
    else:
        return np.nan
        
only_comm['CL4'] =  only_comm['transaction_type'].apply(CL4)

In [9]:
only_comm.head()

,country_or_area,year,transaction_type,unit,quantity,category,CL4
0,Austria,1996,exports,"Metric tons, thousand",5.0,additives_and_oxygenates,NaN
1,Austria,1995,exports,"Metric tons, thousand",17.0,additives_and_oxygenates,NaN
2,Belgium,2014,exports,"Metric tons, thousand",0.0,additives_and_oxygenates,NaN
3,Belgium,2013,exports,"Metric tons, thousand",0.0,additives_and_oxygenates,NaN
4,Belgium,2012,exports,"Metric tons, thousand",35.0,additives_and_oxygenates,NaN

In [10]:
#CL08811 - CL08832 - > CL088

transformation_in_electricity_chp_and_heat_plants = ['main activity',
                                                     'main activity electricity plants',
                                                     'main activity chp plants ',
                                                     'main activity total',
                                                     'main activity heat plants',
                                                     'transformation in main activity producer electricity plants',
                                                     'transformation in main activity producer chp plants',
                                                     'transformation in main activity producer heat plants',
                                                     'transformation in main activity electricity plants',
                                                     'transformation in main activity heat plants',
                                                     'transformation in main activity chp plants',
                                                     'transformation in chp plants main activity producers',
                                                     'transformation in electricity plants main activity producers',
                                                     'transformation in heat plants main activity producers',
                                                     'autoproducer',
                                                     'autoproducer electricity plants',
                                                     'autoproducer chp plants',
                                                     'autoproducer heat plants',
                                                     'autoproducer total',
                                                     'transformation in autoproducer electricity plants',                                 
                                                     'transformation in autoproducer chp plants',
                                                     'transformation in autoproducer heat plants',
                                                     'transformation in chp plants autoproducers',
                                                     'transformation in electricity plants autoproducers',
                                                     'transformation in heat plants autoproducers',
                                                     'other transformation processes not elsewhere classified',
                                                     'from other sources main activity producers',
                                                     'from other sources autoproducers',
                                                     'from other sources total'
                                                    ]

#CL1211 - CL1214 - > CL121
manufacturing_construction_and_non_fuel= ['consumption by iron and steel',
                                          'consumption by chemical and petrochemical',
                                          'consumption by chemical',
                                          'consumption by other manuf., const. and non-fuel',
                                          'consumption by other manufacturing, construction and non-fuel'
                                            ]


#CL1222-CL1225 -> CL122
transport = ['consumption by rail',
             'consumption by road',
             'consumption by domestic navigation',
             'consumption by domestic aviation',
             'consumption by pipeline transport',
             'consumption by other transport',
             'consumption not elsewhere specified (transport)'
            ]


#CL1231-1235 -> CL123
other = ['consumption by households',
        'consumption by agriculture, forestry and fishing',
        'consumption by commercial and public services',
        'consumption by other consumers',
        'consumption by other consumers not elsewhere specified',
        'consumption by other industries and construction',
        'consumption by other',
        'commercial and public services',
        'commercial and public services',
        'consumption not elsewhere specified (other)'
        ]

#cl071
net = [ "net installed capacity of electric power plants public solar",
        "net installed capacity of electric power plants, public combustible fuels",
        "net installed capacity of electric power plants, public geothermal", 
        "net installed capacity of electric power plants, public hydro",  
        "net installed capacity of electric power plants, public nuclear",
        "net installed capacity of electric power plants, public tide, wave, marine",
        "net installed capacity of electric power plants, public wind",
        "net installed capacity of electric power plants, self-producer combustible fuels", 
        "net installed capacity of electric power plants, self-producer geothermal",
        "net installed capacity of electric power plants, self-producer hydro",
        "net installed capacity of electric power plants, self-producer nuclear",  
        "net installed capacity of electric power plants, self-producer solar",
        "net installed capacity of electric power plants, self-producer tide, wave, marine",
        "net installed capacity of electric power plants, self-producer wind", 
        "net production",
        "net transfers",
        "pumped hydro main activity producers",
        "solar pv main activity producers",
        "solar thermal main activity producers",
        "pumped hydro autoproducers",
        'solar pv autoproducers',
        'solar thermal autoproducers',
        'pumped hydro total',
        'solar pv total',
        'solar thermal total'
          ]

In [11]:
def CL3(row):
    if row['transaction_type'] in transformation_in_electricity_chp_and_heat_plants:
        return 'transformation in electricity, chp and heat plants'
    elif row['transaction_type'] in net:
        return 'Transfers details'
    elif row['transaction_type'] in manufacturing_construction_and_non_fuel:
        return 'consumption by manufacturing, construction and non-fuel'
    elif row['transaction_type'] in transport:
        return 'transport'
    elif row['transaction_type'] in other :
        return 'other'
    else:
        return np.nan
    
    
only_comm['CL3'] =  only_comm.apply(CL3, axis=1)

In [12]:
production = ['production from refineries', 
              'production from plants' ,
              'production from off-shore',
              'total production, main activity',
              'total nuclear production', 
              'used for electricity production'
             ]

international_marine_bunkers = ['international marine bunkers',
                                'international aviation bunkers']
#CL088 - CL089 -> CL08
transformation = [# usunięcie 'transformation in electricity, chp and heat plants', 
                    'transformation in coke ovens',
                    'transformation in gas works',
                    'transformation in briquetting plants',
                    'transformation in blast furnaces',
                    'transformation in coal liquefaction plants',
                    'transformation in oil refineries',
                    'transformation in charcoal plants',
                    'transformation in petrochemical plants',
                    'transformation in natural gas blending plants',
                    'transformation in gas-to-liquid plants',
                    'used for electric boilers',
                    'used for heat pumps',
                    'other transformation'
                 ]

#CL0911-CL0928 -> CL09
energy_industries_own_use = ['own use by coal mines',
                            'own use by coke ovens',
                            'own use by gas works',
                            'own use by briquetting plants',
                            'own use by blast furnaces',
                            'own use by oil refineries',
                            'own use by oil and gas extraction',
                            'own use by electricity, chp and heat plants',
                            'own use by coal liquefaction plants',
                            'own use by pump-storage plants',
                            'own use by lng/regasification plants',
                            'own use by nuclear fuel extraction and processing',
                            'own use by biogas production plants',
                            'own use by other energy producers',
                            'own use by gas-to-liquid (gtl) plants',
                            'own use by charcoal plants',
                            'own use by gasworks',
                            'consumption by lng/regasification plants',
                            'consumption by coal mines',
                            'consumption by energy sector',
                            'consumption by briquetting plants', 
                            'conversion in briquetting plants',
                            'conversion in blast furnaces',
                            'other energy industry own use'
                            ]


#CL121-CL123 ->CL12
final_energy_consumption = ['consumption by manufacturing, construction and non-fuel',
                            'consumption by other manuf., const. and non-fuel',
                            'consumption by transport',
                            'consumption by electricity, chp and heat plants'
                            'transport', 
                            'other'
                           ]



#CL07
transfers = [   'total net installed capacity of electric power plants, main activity',
                'total net installed capacity of electric power plants, main activity & autoproducer',
                'total net installed capacity of electric power plants, combustible fuels',
                'total net installed capacity of electric power plants, hydro',
                'total net installed capacity of electric power plants, autoproducer',
                'total net installed capacity of electric power plants, wind',
                'total net installed capacity of electric power plants, solar',
                'total net installed capacity of electric power plants, nuclear',
                'total net installed capacity of electric power plants, geothermal',
                'total net installed capacity of electric power plants, tide, wave, marine',
                'total wind production',
                'total thermal production',
                'total hydro production',
                'total hydraulic resources',
                'total production, autoproducer',
                'total solar production',
                'total geothermal production',
                'total tide, wave production',
                'transfers and recycled products'
              ]  


losses = [ 'extraction loss shrinkage', 'flared' ]

In [13]:
def CL2(row):
    if row['transaction_type'] in production :
        return 'production'
    elif row['transaction_type'] == 'receipts from other sources':
        return ' receipts from other sources'
    elif row['transaction_type'] == 'imports': 
        return 'imports'
    elif row['transaction_type'] == 'exports': 
        return 'exports'
    elif row['transaction_type'] in international_marine_bunkers:
        return 'international marine bunkers'
    elif row['transaction_type'] == 'stock changes':
        return 'stock changes'
    elif row['transaction_type'] in net:
         return 'transfers'
    elif row['transaction_type'] in transformation:
        return 'transformation'
    elif row['transaction_type'] in energy_industries_own_use:
        return 'energy industries own use'
    elif row['transaction_type'] in losses:
        return 'losses'
    elif row['transaction_type'] == 'consumption for non-energy use':
        return 'non-energy use'
    elif row['transaction_type'] in final_energy_consumption:
        return 'final energy consumption'
    else:
        return np.nan
    
only_comm['CL2'] =  only_comm.apply(CL2, axis=1)

In [14]:
only_comm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032032 entries, 0 to 1032031
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   country_or_area   1032032 non-null  category
 1   year              1032032 non-null  category
 2   transaction_type  1026856 non-null  category
 3   unit              1032032 non-null  category
 4   quantity          1032032 non-null  float32
 5   category          1032032 non-null  category
 6   CL4               61974 non-null    object
 7   CL3               277607 non-null   object
 8   CL2               312532 non-null   object
dtypes: category(5), float32(1), object(3)
memory usage: 34.5+ MB

In [15]:
only_comm[only_comm['CL2'].isnull()]['transaction_type'].value_counts()

total energy supply                                                                    76975
final consumption                                                                      63026
final energy consumption                                                               58920
production                                                                             52072
consumption by other                                                                   37679
transformation                                                                         31025
consumption by households                                                              27921
transformation in electricity, chp and heat plants                                     21325
non-energy use                                                                         15572
energy stries own use                                                                  15253
consumption by commercial and public services                                          14051
main activity                                                                          13904
consumption by agriculture, forestry and fishing                                       13227
consumption by road                                                                    12588
consumption by iron and steel                                                          10709
consumption by chemical and petrochemical                                              10605
consumption not elsewhere specified (other)                                            10533
losses                                                                                 10029
consumption by non-metallic minerals                                                    9845
consumption not elsewhere specified (stry)                                              9283
consumption by food and tobacco                                                         8291
transformation in electricity plants main activity producers                            8268
transfers and recycled products                                                         7127
consumption by paper, pulp and print                                                    6945
autoproducer                                                                            6682
consumption by machinery                                                                6357
transformation in electricity plants autoproducers                                      5916
gross demand                                                                            5836
gross production                                                                        5832
consumption by textile and leather                                                      5664
consumption by construction                                                             5584
transformation in chp plants autoproducers                                              5578
consumption by mining and quarrying                                                     5354
consumption by non-ferrous metals                                                       4885
total net installed capacity of electric power plants, main activity & autoproducer     4698
total net installed capacity of electric power plants, main activity                    4698
total net installed capacity of electric power plants, combustible fuels                4668
total thermal production                                                                4665
consumption by wood and wood products                                                   4661
transformation in chp plants main activity producers                                    4265
consumption by transport equipment                                                      4136
consumption by rail                                                                     3924
consumption by domestic aviation                                                        3909
main activity electricity plants                                                        3538
transformation in heat plants main activity producers                                   3276
total net installed capacity of electric power plants, hydro                            3241
total hydro production                                                                  3194
total net installed capacity of electric power plants, autoproducer                     3188
consumption by domestic navigation                                                      3161
total production, autoproducer                                                          3108
consumption by stries not elsewhere specified                                           2828
other energy stry own use                                                               2594
refinery capacity                                                                       2563
transformation in heat plants autoproducers                                             2443
consumption not elsewhere specified (transport)                                         2218
reserves                                                                                1974
memo:gross production                                                                   1972
main activity chp plants                                                                1962
autoproducer electricity plants                                                         1898
autoproducer chp plants                                                                 1636
total net installed capacity of electric power plants, wind                             1347
consumption by other consumers                                                          1319
consumption by other manufacturing, construction and non-fuel                           1315
total wproduction                                                                       1297
consumption by other consumers not elsewhere specified                                  1219
transformation in main activity electricity plants                                      1080
total net installed capacity of electric power plants, solar                            1038
main activity total                                                                     1027
main activity heat plants                                                               1005
transformation in autoproducer chp plants                                                974
flared and vented                                                                        960
consumption by pipeline transport                                                        946
total solar production                                                                   907
total resources                                                                          886
total hydraulic resources                                                                754
autoproducer heat plants                                                                 699
autoproducer total                                                                       662
total net installed capacity of electric power plants, nuclear                           647
transformation in main activity chp plants                                               645
changes in stocks                                                                        643
transformation in main activity producer electricity plants                              638
transformation in autoproducer electricity plants                                        554
transformation in autoproducer heat plants                                               503
total resources in place                                                                 469
re-injected                                                                              463
total net installed capacity of electric power plants, geothermal                        454
total geothermal production                                                              427
total known reserves                                                                     421
transformation in main activity producer chp plants                                      410
recoverable reserves                                                                     366
transformation in main activity heat plants                                              357
consumption by other transport                                                           274
consumption by food, beverage and tobacco                                                252
transformation in main activity producer heat plants                                     251
from other sources total                                                                 204
vented                                                                                   199
additional resources                                                                     169
from other sources autoproducers                                                         161
from other sources main activity producers                                               129
reserves from oil shale and tar sands                                                    119
consumption by stry & construction                                                       119
consumption by other stries and construction                                             111
reserves from oil shale                                                                   86
total net installed capacity of electric power plants, tide, wave, marine                 69
transformation in other energy-producing plants                                           68
recoverable                                                                               61
reasonably assured reserves                                                               61
reserves from tar sands                                                                   55
commercial and public services                                                            53
total tide, wave production                                                               50
consumption by chemical                                                                   42
estimated additional reserves                                                             42
other reserves                                                                             9
consumption by electricity, chp and heat plants                                            9
memo: closing stock level (national territory)                                             8
memo: opening stock level (national territory)                                             8
other transformation processes not elsewhere classified                                    4
conversion in briquetting plants                                                           0
used for heat pumps                                                                        0
used for electricity production                                                            0
total nuclear production                                                                   0
international marine bunkers                                                               0
total production, main activity                                                            0
international aviation bunkers                                                             0
imports                                                                                    0
used for electric boilers                                                                  0
transformation in petrochemical plants                                                     0
transformation in oil refineries                                                           0
flared                                                                                     0
extraction loss shrinkage                                                                  0
exports                                                                                    0
transformation in natural gas blending plants                                              0
transformation in gas works                                                                0
consumption by other manuf., const. and non-fuel                                           0
consumption by briquetting plants                                                          0
consumption by coal mines                                                                  0
consumption by energy sector                                                               0
transformation in blast furnaces                                                           0
transformation in briquetting plants                                                       0
transformation in charcoal plants                                                          0
consumption by lng/regasification plants                                                   0
consumption for non-energy use                                                             0
net installed capacity of electric power plants public solar                               0
consumption by transport                                                                   0
transformation in coal liquefaction plants                                                 0
transformation in coke ovens                                                               0
consumption by manufacturing, construction and non-fuel                                    0
transformation in gas-to-liquid plants                                                     0
conversion in blast furnaces                                                               0
net installed capacity of electric power plants, public nuclear                            0
net installed capacity of electric power plants, public combustible fuels                  0
own use by lng/regasification plants                                                       0
pumped hydro autoproducers                                                                 0
production from refineries                                                                 0
production from plants                                                                     0
production from off-shore                                                                  0
own use by pump-storage plants                                                             0
own use by other energy producers                                                          0
own use by oil refineries                                                                  0
own use by oil and gas extraction                                                          0
own use by nuclear fuel extraction and processing                                          0
own use by gasworks                                                                        0
net installed capacity of electric power plants, public geothermal                         0
own use by gas-to-liquid (gtl) plants                                                      0
own use by gas works                                                                       0
own use by electricity, chp and heat plants                                                0
own use by coke ovens                                                                      0
own use by coal mines                                                                      0
own use by coal liquefaction plants                                                        0
own use by charcoal plants                                                                 0
own use by briquetting plants                                                              0
own use by blast furnaces                                                                  0
pumped hydro main activity producers                                                       0
pumped hydro total                                                                         0
net transfers                                                                              0
receipts from other sources                                                                0
net installed capacity of electric power plants, public hydro                              0
other transformation                                                                       0
net installed capacity of electric power plants, public tide, wave, marine                 0
net installed capacity of electric power plants, public wind                               0
net installed capacity of electric power plants, self-producer combustible fuels           0
net installed capacity of electric power plants, self-producer geothermal                  0
net installed capacity of electric power plants, self-producer hydro                       0
net installed capacity of electric power plants, self-producer nuclear                     0
net installed capacity of electric power plants, self-producer solar                       0
stock changes                                                                              0
solar thermal total                                                                        0
solar thermal main activity producers                                                      0
solar thermal autoproducers                                                                0
solar pv total                                                                             0
solar pv main activity producers                                                           0
solar pv autoproducers                                                                     0
net installed capacity of electric power plants, self-producer tide, wave, marine          0
net installed capacity of electric power plants, self-producer wind                        0
net production                                                                             0
own use by biogas production plants                                                        0
Name: transaction_type, dtype: int64

In [16]:
##nadgrupy
main_category = ['total energy supply','final consumption' ]


#nie wiem gdzie to zaliczyc
wtf = ['refinery capacity', 'gross demand','gross production','reserves' , 
       'memo:gross production' ,'flared and vented ' ,'total resources',
       'total resources in place','re-injected', 'total known reserves',
       'recoverable reserves', 'vented', 'additional resources', 'reserves from oil shale and tar sands',
       'reserves from oil shale', 'reasonably assured reserves', 'recoverable','reserves from tar sands',
       'estimated additional reserves', 'other reserves', 'memo: opening stock level (national territory)', 'memo: closing stock level (national territory)' 
      ]

In [17]:
only_comm.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032032 entries, 0 to 1032031
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   country_or_area   1032032 non-null  category
 1   year              1032032 non-null  category
 2   transaction_type  1026856 non-null  category
 3   unit              1032032 non-null  category
 4   quantity          1032032 non-null  float32
 5   category          1032032 non-null  category
 6   CL4               61974 non-null    object
 7   CL3               277607 non-null   object
 8   CL2               312532 non-null   object
dtypes: category(5), float32(1), object(3)
memory usage: 135.2 MB

In [18]:
only_comm['CL4'] = only_comm['CL4'].astype('category')
only_comm['CL3'] = only_comm['CL3'].astype('category')
only_comm['CL2'] = only_comm['CL2'].astype('category')
only_comm.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032032 entries, 0 to 1032031
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   country_or_area   1032032 non-null  category
 1   year              1032032 non-null  category
 2   transaction_type  1026856 non-null  category
 3   unit              1032032 non-null  category
 4   quantity          1032032 non-null  float32
 5   category          1032032 non-null  category
 6   CL4               61974 non-null    category
 7   CL3               277607 non-null   category
 8   CL2               312532 non-null   category
dtypes: category(8), float32(1)
memory usage: 13.8 MB

In [19]:
# only_comm.to_csv('transaction_type012.csv', index = False)

In [22]:
only_comm2 = only_comm

In [23]:
only_comm2.insert(9,'commodity_transaction', df.commodity_transaction)
only_comm2.insert(10,'commodity', df.commodity)
only_comm2.to_csv('transaction_type013.csv', index = False)

In [24]:
only_comm2

,country_or_area,year,transaction_type,unit,quantity,category,CL4,CL3,CL2,commodity_transaction,commodity
0,Austria,1996,exports,"Metric tons, thousand",5.0,additives_and_oxygenates,NaN,NaN,exports,Additives and Oxygenates - Exports,additives and oxygenates
1,Austria,1995,exports,"Metric tons, thousand",17.0,additives_and_oxygenates,NaN,NaN,exports,Additives and Oxygenates - Exports,additives and oxygenates
2,Belgium,2014,exports,"Metric tons, thousand",0.0,additives_and_oxygenates,NaN,NaN,exports,Additives and Oxygenates - Exports,additives and oxygenates
3,Belgium,2013,exports,"Metric tons, thousand",0.0,additives_and_oxygenates,NaN,NaN,exports,Additives and Oxygenates - Exports,additives and oxygenates
4,Belgium,2012,exports,"Metric tons, thousand",35.0,additives_and_oxygenates,NaN,NaN,exports,Additives and Oxygenates - Exports,additives and oxygenates
...,...,...,...,...,...,...,...,...,...,...,...
1032027,Viet Nam,2012,total wproduction,"Kilowatt-hours, million",92.0,wind_electricity,NaN,NaN,NaN,Electricity - total wind production,electricity
1032028,Viet Nam,2011,total wproduction,"Kilowatt-hours, million",87.0,wind_electricity,NaN,NaN,NaN,Electricity - total wind production,electricity
1032029,Viet Nam,2010,total wproduction,"Kilowatt-hours, million",50.0,wind_electricity,NaN,NaN,NaN,Electricity - total wind production,electricity
1032030,Viet Nam,2009,total wproduction,"Kilowatt-hours, million",10.0,wind_electricity,NaN,NaN,NaN,Electricity - total wind production,electricity
1032031,Viet Nam,2008,total wproduction,"Kilowatt-hours, million",1.0,wind_electricity,NaN,NaN,NaN,Electricity - total wind production,electricity